apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: traefik
  # Configuration TLS (commentée ici, décommentez si nécessaire)
  # tls:
  #   - secretName: fastapi-selfsigned-secret
  #     hosts:
  #       - "{{ .Values.namespace }}.meca.cloudns.ch"
  rules:
  - host: "{{ .Values.namespace }}.meca.cloudns.ch"
    http:
      paths:
        # Configuration du chemin pour l'API de films
        - path: /api/v1/movies
          pathType: Prefix
          backend:
             service:
              name: fastapi-movie-service
              port:
                number: 8000
        # Configuration du chemin pour l'API de castings
        - path: /api/v1/casts
          pathType: Prefix
          backend:
             service:
              name: fastapi-cast-service
              port:
                number: 8000
